Resources:

  ObserverLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.baseName}-observer-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:custom.baseName}-observer-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !Sub arn:aws:logs:${self:provider.region}:${aws:accountId}:log-group:/aws/lambda/${self:custom.baseName}-*:log-stream:*
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: 
                  - !GetAtt SecurityCloudtrailTable.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: 
                  - !Ref SecurityCloudtrailTopic

  SecurityCloudtrailLogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:custom.baseName}-cloudtrail-log-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:custom.baseName}-cloudtrail-log-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - !GetAtt SecurityCloudtrailLogGroup.Arn
