Resources:

  SecurityCloudtrailLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    
  SecurityCloudtrailLogBucketAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecurityCloudtrailLogBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:GetBucketAcl
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource:
              - !Sub arn:aws:s3:::${SecurityCloudtrailLogBucket}
          - Effect: Allow
            Action: s3:PutObject
            Principal:
              Service: cloudtrail.amazonaws.com
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
            Resource:
              - !Sub arn:aws:s3:::${SecurityCloudtrailLogBucket}/*
